# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x0f\x64\x65mo.calculator\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x01\"\x07\n\x05\x45mpty2\x86\x01\n\nCalculator\x12@\n\x03\x41\x64\x64\x12\x1b.demo.calculator.AddRequest\x1a\x1c.demo.calculator.AddResponse\x12\x36\n\x04Ping\x12\x16.demo.calculator.Empty\x1a\x16.demo.calculator.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=37
  _globals['_ADDREQUEST']._serialized_end=71
  _globals['_ADDRESPONSE']._serialized_start=73
  _globals['_ADDRESPONSE']._serialized_end=102
  _globals['_EMPTY']._serialized_start=104
  _globals['_EMPTY']._serialized_end=111
  _globals['_CALCULATOR']._serialized_start=114
  _globals['_CALCULATOR']._serialized_end=248
# @@protoc_insertion_point(module_scope)
